### ISSUE TITLE
Scrollable containers for components

### ISSUE THREAD

**Issue by mnida** [uselotus/lotus#337]
**Is your feature request related to a problem? Please describe.**
When creating a plan with many components, the components fill up the page rather than existing in a set heigh container that can be scrolled up and down to view.

**Describe the solution you'd like**
A scrollable container around the components.

**Comment by glamboyosa** [comment]
Hi I'd like to pick this up 👋🏿

**Comment by mnida** [comment]
Sounds great, go for it!
