### ISSUE TITLE
Add Braintree Payment Integration

### ISSUE THREAD

**Issue by mnida** [uselotus/lotus#447]
**Is your feature request related to a problem? Please describe.**
Customers want to pay through paypal/braintree not just through Stripe

**Describe the solution you'd like**
Add braintree to our payment processor integrations. Similar to Stripe's integration.

This needs to be able to
* issue payments
* issue invoices
* receive webhooks on payment received
* import customers from Braintree and merge into lotus
* create customer in braintree

This should allow the next PSP integration to be much easier since these steps should be fairly reproducible and are already defined for Stripe in an extensible way in the backend.

The last bit of this will be creating a card in the frontend and connecting either via oauth or more easily (MVP) through a secret api key.

**Comment by diego-escobedo** [comment]
Pull request coming along nicely.

Done:

- Write basic methods like create customer, import customer, etc.
- write frontend oauth flow (using https://github.com/NangoHQ/nango)
- separate flow for self-hosted / cloud

Missing:

- Add Braintree icon
- Figure out multi-currency merchants (works diff. from Stripe)... possibly not necessary for a beta release
- webhooks. For now, using a polling strategy to get updates on payments.
- Eventually, implement transfer subs
