### ISSUE TITLE
Plans

### ISSUE THREAD

**Issue by convivitybackendteam** [uselotus/lotus#464]
Hi everyone,

We are looking to use Lago for our membership system but we have an advanced setup and are trying to see if there is a workaround in Lotus. We are an E-Learning company and sell subjects with video teaching and other features. Right now our products have multiple layers and we would like to know if our layering is possible in this system.

We have a Subject(Main Product), for example, Math. In each Subject, we want to have different tier levels with certain features in each tier.

Now, we have curriculums (Sub Product) in that subject, and we want to be able to attach the tiers available for that curriculum. We can have multiple curriculums (books) that have all the tiers or some of the tiers.

Is this something possible or is there a workaround to it?

**Comment by mnida** [comment]
Hi @convivitybackendteam. First off, this is Lotus not Lago.

This is a complex use case, however the great news is that we're working on an add-ons feature that will be able to handle this! This should be released within the next few weeks. My recommendation would be to wait until this is released. In the meantime I can alert you when it is released in our new slack community (https://join.slack.com/t/lotus-community/shared_invite/zt-1fufuktbp-ignnw768aZgdFNlcvAOSrw).

**Comment by convivitybackendteam** [comment]
Hi @mnida Sorry about that, we meant Lotus. To clarify, the Add - On module will allow us to have products within a product and tiers?

**Comment by mnida** [comment]
Yes @convivitybackendteam . We've been spending time designing this feature to support many use cases including the layers you mentioned. I don't believe any other billing software will be able to do this once we've released it.

**Comment by mnida** [comment]
Closing this now as I think we have found a solution to their edge case without our add-ons necessarily.

**Comment by diego-escobedo** [comment]
For posterity, we did add add-ons in https://github.com/uselotus/lotus/pull/463. Currently we are only allowing addon creation, and addon attaching must be done exclusively through the API/SDK. If you are interested in exploring please let us know so we can set up a sandbox account for you.
