### ISSUE TITLE
Windows docker compose Dev bug

### ISSUE THREAD

**Issue by mnida** [uselotus/lotus#507]
**Describe the bug**
Running dev and self-host on docker-compose doesn't work with our script. This is most likely an issue with our script or our docker not running on windows 64 correctly

**To Reproduce**
1. Follow contributing dev instructions
2. Run the ./scripts/dev.sh on the windows machine

**Expected behavior**
Docker compose should be running, including the backend container instead of erroring like below.
**Screenshots**
![image (2)](https://user-images.githubusercontent.com/33556500/215581689-e3d0516b-d5b2-4c30-aeca-097b15b03813.png)

**Desktop (please complete the following information):**
 - OS: Windows, potentially only windows 64
 - Browser: N/A
 - Version 0.9.1

**Comment by harrisyn** [comment]
yeah, been trying to run this for the last 3hrs, same error
platform is windows 64bit

**Comment by mnida** [comment]
Hey @harrisyn. We've made some fixes on this over the past week and are pushing it out in a few days. I'll ping you again when its out!

**Comment by harrisyn** [comment]
Thanks for the update, look forward to hearing from you
