### ISSUE TITLE
Improving packaging

### ISSUE THREAD

**Issue by bioinfornatics** [uselotus/lotus#530]
Dear,
after a look to the code, to my point of view providing a mix of Pipfile and pyproject.toml do not aims a gold standard.
Ideally, the build process have to generate a distributable archive such as a wheel.
The generated wheel is mount to the container and installed with help pip

Thus I would recommend to use poetry, which help a lot and ease this process

Best regards

**Comment by mnida** [comment]
Hi,
Will loop in @diego-escobedo on the convo as he is the python lead on this project.

**Comment by mnida** [comment]
What do we think about Poetry vs pdm? @bioinfornatics

**Comment by bioinfornatics** [comment]
tooling is sometime subjective, I use poetry and fit well the needs. They are active and continue to add features.
if `pdm` is the right tools for you it is nice too
here I think the build process need to be well split:
- build -> declare the `main`
as example for a `pyproject.toml`
```toml
…
[tool.poetry.scripts]
lotus_backend = "lotus.backend.__main__:main"
…
```
- archive -> wheel
- install -> mount wheel to the container and pip install


thanks to this works and to provides such tools

**Comment by mnida** [comment]
@bioinfornatics Makes sense. I'm open to either poetry or pdm. I like how you broke down the process. Would you be open to starting this issue?

**Comment by bioinfornatics** [comment]
to give an insight to the road to take: https://github.com/uselotus/lotus/pull/547

**Comment by mnida** [comment]
Amazing @bioinfornatics!

**Comment by diego-escobedo** [comment]
Hey @bioinfornatics never heard anything else from you on that PR you linked. The codebase has changed quite a bit since then so I'm closing this + the PR for now but feel free to reopen once the changes are a bit less drastic.
