### ISSUE TITLE
Webhook for subscription cancellation/ending

### ISSUE THREAD

**Issue by djanda97** [uselotus/lotus#592]
**Is your feature request related to a problem? Please describe.**
Users want a webhook when a subscription is cancelled/ends.
 
**Describe the solution you'd like**
In the backend add this webhook functionality using our alerts framework and svix.

In the frontend simply add the checkbox in the create webhook url form.

**Comment by Aashish-Upadhyay-101** [comment]
hi I want to work on this issue, please assign me this !

**Comment by djanda97** [comment]
Hi @Aashish-Upadhyay-101! I haven't started implementing this webhook yet, so feel free to work on it!
#440 and #539 will be helpful to reference as they include the files required for adding new webhook events.
