### ISSUE TITLE
UI bug: Misaligned checkboxes on Developer Settings tab

### ISSUE THREAD

**Issue by djanda97** [uselotus/lotus#610]
**Describe the bug**
The checkboxes on the `Webhook URL` modal are not aligned

**To Reproduce**
1. Start the dev server by executing `./scripts/dev.sh`
2. Once the dev server is running, navigate to [http://localhost:8000/settings/developer-settings](http://localhost:8000/settings/developer-settings)
3. Click the `Add URL` button near the `Webhooks` section of the page
4. Once the `Webhook URL` modal appears, notice that the checkboxes are not aligned

**Expected behavior**
The checkboxes should be vertically and horizontally aligned

**Screenshots**

![image](https://user-images.githubusercontent.com/8923819/221095952-43279bf6-2b60-4cf8-b1ca-b6860ab81281.png)

**Desktop**
 - OS: MacOS 13.2.1
 - Browser: Firefox
 - Version: 110.0
 - Browser: Safari
 - Version: 16.3

**Comment by mnida** [comment]
@djanda97 If you don't pick this up, I have another person who can fix it at the start of the week!

**Comment by djanda97** [comment]
@mnida I don't have much experience with CSS, but I'd like to try fixing this one!

**Comment by djanda97** [comment]
It appears that the `Checkbox` component provided by the `antd` library is implicitly applying an 8px left margin to the generated HTML elements:

![image](https://user-images.githubusercontent.com/8923819/221393807-500808ef-5f22-48dd-a85e-c6632c3e6957.png)

Strangely, the 8px left margin only affects the last three checkboxes.

I was able to get the checkboxes aligned correctly by setting the style prop of the `Checkbox` components to use a 0px left margin, but I'm wondering if there are better ways of handling this.
