### ISSUE TITLE
Fix Plan Version Status Component Design

### ISSUE THREAD

**Issue by mnida** [uselotus/lotus#619]
**Is your feature request related to a problem? Please describe.**
The design for the component right now is not as clean as we envisioned. Part of this is that it stretches out too much. Here is a pic of what is looks like now on a Mac 16 inch.
<img width="951" alt="Screen Shot 2023-02-28 at 12 20 41 AM" src="https://user-images.githubusercontent.com/33556500/221794873-6abd99d6-aabd-4ebd-beec-f3b1ad44f6c5.png">

Here is what is looks like on a monitor. Way too stretched out as you can see.
![Screen Shot 2023-02-28 at 12 21 13 AM](https://user-images.githubusercontent.com/33556500/221794959-e0d279ac-cd32-4893-98ee-da9d5c8d3798.png)

**Describe the solution you'd like**
![Frame 986254](https://user-images.githubusercontent.com/33556500/221797258-03ae2d4d-a786-4347-a412-70a5b55a9302.jpg)
![Frame 986249](https://user-images.githubusercontent.com/33556500/221797600-a713a837-2a4d-4390-a996-a4a704f355bf.jpg)

Instead we would prefer a component that is consistent across monitors (fixed width) and matches this design here. This issue only covers the gray pill with active, grandfathered, retiring, inactive and the three dots inside it. That is the component in question.

In addition, make sure the 3 dots on the side of the component are centered correctly that match the design above.

Please check on large screen sizes as well.

**Comment by iamoghenerukevwe** [comment]
Can I pick this  up?

**Comment by mnida** [comment]
Go for it @iamoghenerukevwe!

**Comment by mnida** [comment]
Hey @iamoghenerukevwe . Looks like someone has already picked this one up

**Comment by diego-escobedo** [comment]
Closed by #624  and #626
