### ISSUE TITLE
Cypress Tests Failing

### ISSUE THREAD

**Issue by diego-escobedo** [uselotus/lotus#633]
Now that cypress tests have been unblocked and are successfully running, we need to get them to actually test what we need them to:

https://github.com/uselotus/lotus/actions/runs/4325586762/jobs/7551940059

**Comment by djanda97** [comment]
I have a bit of experience with Cypress and UI testing in general so I would be up for working on this issue!

**Comment by mnida** [comment]
Awesome @djanda97. Putting you on this now
