### ISSUE TITLE
Move draft invoice to be a method inside the customer Viewset

### ISSUE THREAD

**Issue by diego-escobedo** [uselotus/lotus#652]
Currently, draft invoice is its own method in the views.py file. Since the only relevant input to draft_invoice is the custoemr's ID, it doesn't make sense to have it as a standalone method. Instead, we should reduce the repetitiveness of the code by adding it as a method in the customerviewset (perhaps the one in api, so we can eventually expose it to the public). This will allow us to use explicit paths /customers/{customer_id}/draft_invoice/ when referencing it and reuse the viewset's identification code. 

To be considered complete, we need:
1. transfer logic to the customer viewset
2. regenerate schemas
3. change the frontend urls pointing from the old endpoint to the new one

**Comment by Aashish-Upadhyay-101** [comment]
I want to work on this.

**Comment by diego-escobedo** [comment]
Resolved by https://github.com/uselotus/lotus/pull/684
