### ISSUE TITLE
Add code coverage into pytest

### ISSUE THREAD

**Issue by diego-escobedo** [uselotus/lotus#653]
Current commands I've been using locally is `pytest --cov=. --cov-report term-missing`, but need to add it into the CI, and make sure that it fails if its under the current level. Believe I currently have some unimportant files commented out by .coveragerc, but would be good to look through the coverage report to see what else is extra. Once we have this, we can establish a baseline to 1. never dip under and 2. improve on

**Comment by Aashish-Upadhyay-101** [comment]
I want to work on this :D

**Comment by diego-escobedo** [comment]
💪
