### ISSUE TITLE
Add bulk pricing

### ISSUE THREAD

**Issue by diego-escobedo** [uselotus/lotus#654]
This is what our current plan component creation screen looks like:

![Screenshot 2023-03-11 at 5 13 23 PM](https://user-images.githubusercontent.com/36511112/224518855-25935036-aafb-433e-9f82-7f1e80dd4384.png)

This all-tiers structure gives us maximum flexibility, as it lets us represent multiple formats easily: tiered pricing, flat rates, minimums + overages, free units, etc. However, the one functionality we're missing is bulk pricing.

In bulk pricing, instead of charging the first 50 units at one price, the next 50 at another, etc. as we currently do in the tiers, we would charge ALL the units at the price of the tier the usage fell into. So if we have 50 units they all get charged at the price of the 0-50 tier, if we have 100 they all get charged at the price of the 50-100 tier. 

In order to achieve this, we need the following:
1. Add a new field to the plan component model indicating if the tiers are volume tiers. 
2. Edit the `calculate_total_revenue` in the plan components and the `calculate_revenue` method in the tier model in order to be able to handle this new case. 
3. Edit the serialization of PlanComponents to be able to accept it when incoming (`PlanComponentCreateSerializer` and `PlanComponentSerializer`)
4. Add a checkbox or some sort of visual component in the frontend (frontend/src/components/Plans/UsageComponentForm.tsx) to indicate its bulk pricing
5. Make sure frontend is passing the new field correctly to the backend.
6. Add tests for bulk pricing.

**Comment by jaysoni-ash42** [comment]
@diego-escobedo  i want to work on this issue can you  specify the description of the issue a bit more?

**Comment by diego-escobedo** [comment]
Hey Jay! Just added a lot more detail let me know if there's anything else you need

**Comment by mnida** [comment]
Hey @jaysoni-ash42. Any updates on this?

**Comment by mnida** [comment]
Hey @jaysoni-ash42 , we will be reassigning the issue can you provide an update?

**Comment by jaysoni-ash42** [comment]
@mnida stucked with some work you can assign this to someone else in the mean time.
