### ISSUE TITLE
Route to original page after login

### ISSUE THREAD

**Issue by diego-escobedo** [uselotus/lotus#708]
Right now, we send you to the dashboard screen after you log in every time. Instead, what we should be doing is sending you to the page you wanted to go to originally (e.g. /settings/integrations/). This can probably be fixed from the routes page

**Comment by Aashish-Upadhyay-101** [comment]
so right now i think we have `redirectDashboard()` that takes to dashboard page after `Authentication.login()` right?
and we just want to redirect to something like `settings/integrations`  on successful login. is this the problem statement?
so it's just a small fix, right?

**Comment by diego-escobedo** [comment]
So it should be dependent on where the user originally wanted to go. They could have entered the address https://app.uselotus.io/customers/cust_654d47b61457486f19c7787a59e27 because they're trying to look at a specific customers data. However , as you noted, they will be redirected to Dashboard. The idea is not matter what they enter, to navigate them to that page upon successful authentication. Does that make sense?

**Comment by diego-escobedo** [comment]
Resolved! Nice job @Aashish-Upadhyay-101 💪
