### ISSUE TITLE
difference between lotus and stigg.io ? 

### ISSUE THREAD

**Issue by Geczy** [uselotus/lotus#762]
https://www.stigg.io/

just saw this on producthunt, was going to integrate with lotus but not sure which one to use now. any ideas?

**Comment by mnida** [comment]
Hi @Geczy , Lotus isn't as dependant on Stripe as Stigg is I believe, in addition, we offer more customizability around aggregations.

They have better graphs and analytics in their app. Also it will probably be easier to get up and running with stigg faster but much less customizable right after that (if you change payment providers or need webhook setup etc.)

**Comment by Geczy** [comment]
does lotus offer localized pricing? https://docs.stigg.io/docs/price-localization

**Comment by mnida** [comment]
Nope
