### ISSUE TITLE
Bulk tiers broke plan creation with components

### ISSUE THREAD

**Issue by yusmpgroup** [uselotus/lotus#766]
**Describe the bug**
When creating a new plan with a single component (bulk price is Off) server responds with error 500:

**To Reproduce**
1. Following instructions on website (https://docs.uselotus.io/overview/self-hosting):
2. Install a fresh copy of Lotus (branch main, commit=760831722c344a825ff1b6549fdca73223e39e6a)
3. Create a metric
4. Create a plan
5. Add Component with the created Metric
6. Click publish
Request payload:
```
{"plan_name":"test2","plan_duration":"monthly","initial_version":{"version":1,"localized_name":null,"recurring_charges":[],"components":[{"metric_id":"metric_368864360fc147a08302d1cd6001571b","tiers":[{"type":"per_unit","range_start":0,"batch_rounding_type":"no_rounding","metric_units_per_batch":1,"cost_per_batch":1,"range_end":1000},{"range_start":1000,"type":"per_unit","cost_per_batch":1,"batch_rounding_type":"no_rounding","metric_units_per_batch":1}],"prepaid_charge":null}],"features":[],"usage_billing_frequency":"monthly","currency_code":"USD","plan_name":"test2","day_anchor":1}}
```
Server response:
```
'NoneType' object has no attribute 'tiers'
```

**Expected behavior**
Plan is created

**Details**

The error occurs in file backend/metering_billing/models.py 
![Screenshot from 2023-04-14 11-33-17](https://user-images.githubusercontent.com/83700907/231942545-6aa91376-2376-43ad-9347-f4d1512ab3a0.png)

**Comment by mnida** [comment]
This was fixed by @diego-escobedo last week.
