### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by pydubreucq** [uselotus/lotus#770]
Hi,
I just would like to know if this project is still active or not ?
Thanks by advance.
Best Regards,
Pierre-Yves

**Comment by mnida** [comment]
@pydubreucq we are however still here to fix bugs

**Comment by inventionlabsSydney** [comment]
@mnida Just to clarify, the project wont have any further features ever?
So it's now just in a maint status?

Can I ask the reason?

**Comment by mnida** [comment]
Yes, maintenance status! It's because we no longer have a business/monetary support to fund full time support for the project. The goal is now an open source community but we need to recruit more contributors if we want to add more features.
