### ISSUE TITLE
Addons description field required on backend

### ISSUE THREAD

**Issue by devel-pa** [uselotus/lotus#779]
Add on description not marked as required, but required by the backend

**To Reproduce**
1. Go to Create Add Ons page
2. Write name
3. Click on Preview & publish

**Expected behavior**
Save addon

**Desktop (please complete the following information):**
 - OS: PopOS!
 - Browser Chrome

**Additional context**
Version at commit 9b34b94
Updated timescale at pg16 and svix at 1.15

**Comment by mnida** [comment]
Great catch again @diego-escobedo can take this one I believe.
