### ISSUE TITLE
Inquiry Regarding Switching Dependency from Redpanda to Kafka

### ISSUE THREAD

**Issue by ZekiLiu** [uselotus/lotus#791]
Dear lotus Team,

I hope this message finds you well. I am reaching out to inquire about the possibility of transitioning our current dependency from Redpanda to Kafka within the lotus project.

As I understand, Redpanda is designed to be compatible with Kafka, offering similar functionalities and performance benefits. This compatibility has led me to consider whether Kafka could serve as a viable alternative for our project needs, potentially simplifying our technology stack or aligning better with our existing infrastructure.

However, I am aware that Redpanda offers unique features and optimizations that are not present in Kafka. Before suggesting any changes, I wanted to consult with the team to understand if our project's current usage of Redpanda leverages any of these special characteristics. If so, it would be crucial to evaluate the feasibility and impact of such a transition carefully.

Could you please provide insights into whether our project's implementation is tightly coupled with Redpanda's specific features? Additionally, if a switch to Kafka is deemed possible, I would appreciate any guidance or considerations we should take into account during the evaluation process.

Thank you for your time and attention to this matter. I look forward to your valuable feedback and am happy to discuss this further if needed.

Best regards.

**Comment by mnida** [comment]
It should be fairly Kafka compatible. If I remember correctly for the old cloud program we used Kafka at the beginning. I will loop in @diego-escobedo who should be able to confirm this

**Comment by ZekiLiu** [comment]
Thank you for your response. I appreciate the information regarding the compatibility with Kafka for the old cloud program.

> It should be fairly Kafka compatible. If I remember correctly for the old cloud program we used Kafka at the beginning. I will loop in @diego-escobedo who should be able to confirm this
